services:
  postgres:
    image: postgres:16
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"  # Exposing Postgres on port 5400 for access from pgAdmin or other services
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

 # worker:
  #  build: ./backend/worker  # or a separate ./worker folder if code is split
   # depends_on:
    #  - redis

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    logging:
      driver: "none"      


  pgadmin:
    image: dpage/pgadmin4:latest  # Official pgAdmin image
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}  # Set the default email for login
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}  # Set the default password for login
    ports:
      - "5050:80"  # Expose pgAdmin on port 5050
    volumes:
      - pgadmin_data:/var/lib/pgadmin  # Persist pgAdmin data
    logging:
      driver: "none"

volumes:
  pgdata:  # For Postgres data
  pgadmin_data:  # For pgAdmin data
