# Use a Node.js base image
FROM node:22

# Set the working directory inside the container
WORKDIR /app


# Copy all other files into the container
COPY . .

# Make sure the worker file has execution permissions
RUN chmod +x worker.js

# Run the worker script when the container starts
CMD ["node", "worker.js"]
